name: Deploy to DigitalOcean Server

on:
  pull_request:
    branches: 
      - deployment
    types:
      - closed

permissions:
  contents: read

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
    
    - name: Logon to Server & Pull from GitHub
      run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd /home/personalsite/personal-site && git checkout deployment && git pull origin deployment"
          echo "Successfully pulled from repo."

    - name: Build and Run application
      run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd /home/personalsite/personal-site\
          && tmux kill-session -t website;\
          tmux new -d -s website && tmux send-keys -t website \"./mvnw verify && java -jar target/personalsite-0.0.1-SNAPSHOT.jar\" ENTER"
          echo "Successfully ran new deployment."

