name: Linting and Testing

on:
  push:
    branches:
      - main
      - deployment
      - testing-ci
  pull_request:
    branches:
      - main
      - deployment
      - testing-ci

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        ./mvnw verify --file pom.xml
